label: Hero
status: ready

context:
  hero:
    callout: "FDA’s Visual Identity Program"
    title: false
    paragraph: Establishing and maintaining trust and integrity  through a standard and uniform visual identity.
    button:
      text: Learn why visual identity is a priority for FDA.
      href: "javascript:void(0)"
