label: Primary (header)
preview: "@uswds-header"
status: ready

context:
  nav:
    search: false
    links:
      - text: Home
        is_current: true
      - text: Requirements and Downloads
        id: nav-section-one
        links: &subnav_links
          - text: Navigation link
            href: "#"
          - text: Navigation link
            href: "#"
            is_current: false
          - text: Navigation link
            href: "#"
          - text: Navigation link
            href: "#"
          - text: A very long navigation link that goes onto two lines
            href: "#"
          - text: Navigation link
            href: "#"
          - text: Navigation link
            href: "#"
          - text: Navigation link
            href: "#"
          - text: Navigation link
            href: "#"
      - text: Standards and Best Practices
        id: nav-section-two
        links: *subnav_links
      - text: Why Visual Identity
        href: "javascript:void(0)"
      - text: FAQs
        href: "javascript:void(0)"
      - text: Connect With Us
        href: "javascript:void(0)"
